Repository lbfm-rwth/GaussPar, pull requests merged in 2018-12, with the labels that each got.

#116 Clean up whitespace
  gap/dependencies.g
  gap/main.g
Labels: clean-up

#122 Move measure.tst into stats/ subfolder
  tst/stats/measure-contention.tst
Labels: tests

#123 HPC-GAP and GAP test parallel and sequential each
  tst/testall.g
Labels: tests

#133 Rename function `MKR` to fit naming conventions
  gap/subprograms.g
Labels: short

#131 Make return values of all low-lvl functions read-only
  gap/subprograms.g
Labels: enhancement

#134 Change output of Chief to match Gauss Package
  gap/main.g
  gap/measure_contention.g
  tst/parallel/chiefparallel.tst
  tst/parallel/echelon_form.tst
  tst/standard/chief.tst
  tst/standard/echelon_form.tst
  tst/testfunctions.g
Labels: short

#139 Fixes fault in the global functions and a comment
  gap/main.g
  gap/main.gi
Labels: short
